name: Github Actions Maven Build Example

on:
  push:
    branches:
      - "main"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout main branch from Github
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Step 3 - Have Github Actions Build Maven Project
        run: mvn -B package --file pom.xml
